name: movieetlite
description: Movieet is a movie list track app.

publish_to: 'none'


version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Core
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3

  #Localization
  easy_localization: ^3.0.1

  #Network
  dio: ^4.0.6

  #Analytics
  sentry_flutter: ^6.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  bloc_test: ^9.0.3



flutter:

  uses-material-design: true
  assets:
    - assets/translations/
