name: movieetlite
description: Movieet is a movie list track app.

publish_to: 'none'


version: 0.0.1+1

environment:
  sdk: ">=2.17.5 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #Core
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  flutter_dotenv: ^5.0.2
  

  #Localization
  easy_localization: ^3.0.1

  #Network
  chopper: ^4.0.6

  #Analytics
  sentry_flutter: ^6.6.0

  #Utils
  stream_transform: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  very_good_analysis: ^3.0.1
  bloc_test: ^9.0.3
  mocktail: ^0.3.0
  
  #Code generators
  build_runner: ^2.1.11
  chopper_generator: ^4.0.6
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0


flutter:

  uses-material-design: true
  assets:
    - .env
    - assets/translations/
